version: '3.8'
services:
  api:
    build: .
    container_name: auth_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - sqlite_data:/app/Data

volumes:
  sqlite_data:
