version: "3.8"
services:
  auth_api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - sqlite_data:/app/db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Auth=Data Source=/app/db/auth.db

volumes:
  sqlite_data:
