services:
  api:
    build: .
    container_name: auth_api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - sqlite_data:/app/Data

volumes:
  sqlite_data:
